version: '3'

services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: kinchaku-app
        restart: unless-stopped
        tty: true
        ports:
            - "5000:5000"
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
            APP_ENV: local
            APP_DEBUG: 1
            APP_URL: ${APP_URL}
            DATABASE_URL: ${DB_CONNECTION}://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}
            XDEBUG_CONFIG: client_host=${XDEBUG_REMOTE_HOST} client_port=${XDEBUG_STORM_PORT}
            PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}
        working_dir: /app
        volumes:
            - .:/app
            - ./volumes/nginx/log:/var/log/nginx
        networks:
            - app-network

    postgres:
        image: postgres:13-alpine
        container_name: kinchaku-postgres
        ports:
            - "${DB_PORT}:${DB_PORT}"
        restart: unless-stopped
        tty: true
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            DB_DATABASE_TESTING: ${DB_DATABASE_TESTING}
        volumes:
            - pg-data:/var/lib/postgresql/data
            - ./docker/postgres:/docker-entrypoint-initdb.d
        networks:
            - app-network
networks:
    app-network:
        driver: bridge

volumes:
    pg-data:
        driver: local
